apiVersion: v1
kind: Secret
metadata:
  name: wazuh-api-cred
data:
  username: {{ .Values.secrets.wazuhApiCred.username | b64enc }}
  password: {{ .Values.secrets.wazuhApiCred.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: dashboard-cred
data:
  username: {{ .Values.secrets.dashboardCred.username | b64enc }}
  password: {{ .Values.secrets.dashboardCred.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: indexer-cred
data:
  username: {{ .Values.secrets.indexerCred.username | b64enc }}
  password: {{ .Values.secrets.indexerCred.password | b64enc }}
---
kind: Secret
apiVersion: v1
metadata:
  name: wazuh-cluster-key
data:
  key: {{ .Values.secrets.wazuhClusterKey | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: wazuh-authd-pass
data:
  authd.pass: {{ .Values.secrets.wazuhAuthdPass | b64enc }}
