secrets:
  wazuhApiCred:
    username: wazuh-wui
    password: MyS3cr37P450r.*-
  # Note: need to change the password hash in the indexer user config
  dashboardCred:
    username: kibanaserver
    password: admin
  # Note: need to change the password hash in the indexer user config
  indexerCred:
    username: admin
    password: SecretPassword
  wazuhAuthdPass: password
  wazuhClusterKey: "123a45bc67def891gh23i45jk67l8mn9"


dashboard:
  image: wazuh/wazuh-dashboard:4.7.3
  resources:
    limits:
      memory: 1Gi
  config:
    server.host: 0.0.0.0
    server.port: 5601
    opensearch.hosts: https://indexer:9200
    opensearch.ssl.verificationMode: none
    opensearch.requestHeadersWhitelist: [ authorization,securitytenant ]
    opensearch_security.multitenancy.enabled: false
    opensearch_security.readonly_mode.roles: ["kibana_read_only"]
    server.ssl.enabled: true
    server.ssl.key: "/usr/share/wazuh-dashboard/certs/tls.key"
    server.ssl.certificate: "/usr/share/wazuh-dashboard/certs/tls.crt"
    opensearch.ssl.certificateAuthorities: ["/usr/share/wazuh-dashboard/certs/ca.crt"]
    uiSettings.overrides.defaultRoute: /app/wazuh

indexer:
  image: wazuh/wazuh-indexer:4.7.3
  resources:
    limits:
      memory: 1564Mi
  config:
    users:
      _meta:
        type: "internalusers"
        config_version: 2

      # Get bcrypt hash value with the following command
      # docker run --rm -ti wazuh/wazuh-indexer:4.7.3 bash /usr/share/wazuh-indexer/plugins/opensearch-security/tools/hash.sh
      # The current hashes are default values.
      admin:
        hash: "$2y$12$K/SpwjtB.wOHJ/Nc6GVRDuc1h0rM1DfvziFRNPtk27P.c4yDr9njO"
        reserved: true
        backend_roles:
        - "admin"
        description: "Demo admin user"

      kibanaserver:
        hash: "$2a$12$4AcgAt3xwOWadA5s5blL6ev39OXDNhmOesEoo33eZtrq2N0YrU3H."
        reserved: true
        description: "Demo kibanaserver user"

    opensearch:
      network.host: "0.0.0.0"
      node.name: "wazuh.indexer"
      path.data: /var/lib/wazuh-indexer
      path.logs: /var/log/wazuh-indexer
      discovery.type: single-node
      http.port: 9200-9299
      transport.tcp.port: 9300-9399
      compatibility.override_main_response_version: true
      plugins.security.ssl.http.pemcert_filepath: /usr/share/wazuh-indexer/certs/node/tls.crt
      plugins.security.ssl.http.pemkey_filepath: /usr/share/wazuh-indexer/certs/node/tls.key
      plugins.security.ssl.http.pemtrustedcas_filepath: /usr/share/wazuh-indexer/certs/node/ca.crt
      plugins.security.ssl.transport.pemcert_filepath: /usr/share/wazuh-indexer/certs/admin/tls.crt
      plugins.security.ssl.transport.pemkey_filepath: /usr/share/wazuh-indexer/certs/admin/tls.key
      plugins.security.ssl.transport.pemtrustedcas_filepath: /usr/share/wazuh-indexer/certs/admin/ca.crt
      plugins.security.ssl.http.enabled: true
      plugins.security.ssl.transport.enforce_hostname_verification: false
      plugins.security.ssl.transport.resolve_hostname: false
      plugins.security.ssl.http.clientauth_mode: OPTIONAL
      plugins.security.authcz.admin_dn:
      - "CN=admin,OU=Wazuh,O=Wazuh,L=California,C=US"
      plugins.security.check_snapshot_restore_write_privileges: true
      plugins.security.enable_snapshot_restore_privilege: true
      plugins.security.nodes_dn:
      - "CN=wazuh.indexer,OU=Wazuh,O=Wazuh,L=California,C=US"
      plugins.security.restapi.roles_enabled:
      - "all_access"
      - "security_rest_api_access"
      plugins.security.system_indices.enabled: true
      plugins.security.system_indices.indices: [".opendistro-alerting-config", ".opendistro-alerting-alert*", ".opendistro-anomaly-results*", ".opendistro-anomaly-detector*", ".opendistro-anomaly-checkpoints", ".opendistro-anomaly-detection-state", ".opendistro-reports-*", ".opendistro-notifications-*", ".opendistro-notebooks", ".opensearch-observability", ".opendistro-asynchronous-search-response*", ".replication-metadata-store"]
      plugins.security.allow_default_init_securityindex: true
      cluster.routing.allocation.disk.threshold_enabled: false

manager:
  image: wazuh/wazuh-manager:4.7.3
  resources:
    limits:
      memory: 512Mi
  gcp:
    enabled: false
    # Export a GCP Service Account key as json and put it base64 encoded below
    serviceAccountKeyBase64: ""
    pullOnStart: "yes"
    interval: 1m
    projectId: ""
    subscriptionId: ""

